openwisp/django-loci

.travis.yml
requirements-test.txt
runcheckmigration

For ensuring the migrations created
have have been renamed to something
more descriptive
Closes #12

[ci] Add CI check for migrations

---

.travis.yml
requirements-test.txt
requirements.txt

[qa] Added messages style check #14

---

.travis.yml
requirements-test.txt
requirements.txt
tests/settings.py

[ci] Updated some dependencies and fix build

---

requirements.txt

Added support of new version of django-leaflet
Fixes #26

[dependencies]

---

requirements.txt

Allowed Support For Django2.2
Fixes #25

[dependencies] Add support for django 2.2 #25

---

.travis.yml

Added Support for python 3.7
Dropped Support for django 1.11
Fixes #24

[build] Test multiple django and python versions

---

django_loci/base/admin.py
django_loci/static/django-loci/js/floorplan-widget.js

Fixed frontend bug introduced in Django 2.2 update

[bug] Fixed frontend bug

---

.travis.yml

[Travis] Fix Warning

---

django_loci/base/admin.py
django_loci/tests/base/test_admin_inline.py

[admin] Fixed type KeyError exception during form validation #19

---

.travis.yml
requirements-test.txt
runcheckmigration
runflake8
runisort

Replace old qa checks with `openwisp-utils-qa-checks` (related to openwisp/openwisp-utils#63 for this repo)

[qa] Replace with openwisp-utils-qa-checks

---

django_loci/static/django-loci/js/loci.js

This will prevent geographic location (that was hidden by turning on isMobile) to be showed when Type environment changed.
Fixes #34

[ux] Fix isMobile UI inconsistency

---

django_loci/static/django-loci/js/loci.js

[ux] Floorplan fields bugfix #35

---

django_loci/base/admin.py
django_loci/static/django-loci/js/loci.js
django_loci/tests/base/test_admin.py

The issue was due to the fact that the geometry
is set to None when is_mobile is True and we were
try to get the json of NoneType.
I resolved the problem by making sure the json
function is not called on a NoneType
This fixes [this issue](https://github.com/openwisp/openwisp-controller/issues/35) in openwisp_controller
Fixes #c35

[geo] Fixed JS logic crashes #c35

---

CHANGES.rst
django_loci/__init__.py

Signed-off-by: Ajay Tripathi <ajay39in@gmail.com>

0.3.3 release

---

requirements.txt

Increased Pillow range to allow new 8.0.0 version.

[deps] Increased Pillow range to allow new 8.0.0 version

---

README.rst
django_loci/apps.py
django_loci/base/admin.py
django_loci/base/geocoding_views.py
django_loci/settings.py
django_loci/static/django-loci/js/loci.js
django_loci/tests/base/test_admin.py
django_loci/tests/base/test_apps.py
django_loci/tests/test_apps.py
requirements.txt
tests/settings.py

[feature] Auto calculate geo coords or addr

---

django_loci/base/admin.py
django_loci/tests/base/test_admin_inline.py

[bug] NOT NULL constraint failed: django_loci_floorplan.floor #65

---

django_loci/base/admin.py
django_loci/static/django-loci/js/loci.js
django_loci/templates/admin/django_loci/location_change_form.html
django_loci/tests/base/test_admin.py

- Fixed regression tests which were failing
on openwisp_controller because of poorly
setup url
- Made map's urls dynamic
Closes #44

[fix] Fix automatic geocoding in extended apps (eg: openwisp-controller) #44

---

django_loci/base/admin.py
django_loci/tests/base/test_admin_inline.py

[fix] Ignores is_mobile False from device #62

---

django_loci/channels/routing.py
django_loci/migrations/0001_initial.py
django_loci/tests/testdeviceapp/migrations/0001_initial.py
django_loci/widgets.py
requirements-test.txt
requirements.txt
tests/settings.py
tests/urls.py

Updated requirements to support both openwisp-utils versions, i.e. 0.6 and 0.7
Closes #77

[refactor] Support for openwisp-utils versions 0.6 and 0.7 #77

---

.github/workflows/ci.yml

Workaround the spatialite issue
https://code.djangoproject.com/ticket/32935

[ci] Set CI to run on Ubuntu 20.04

---

requirements.txt

[deps] Pillow~=9.4.0

---

.github/workflows/ci.yml
tests/openwisp2/settings.py

Related to https://github.com/openwisp/openwisp-utils/pull/351 and https://code.djangoproject.com/ticket/32935.

[fix] Workaround for spatialite issue on Ubuntu 22.04 LTS

---

.github/workflows/version-branch.yml
CHANGES.rst
django_loci/__init__.py
requirements-test.txt
requirements.txt

[ci] Added GitHub workflow to replicate commits to version branch

---

requirements-test.txt
requirements.txt

[deps] Install channels dependencies from openwisp-utils extras

---

.github/workflows/ci.yml
django_loci/storage.py
requirements.txt

Closes #155.
1. Updated django channels to 4.2 latest
2. Added daphne~=4.0.0 required to work Django channels
3. Added DEFAULT_FILE_STORAGE path in `storage.py`
4. Updated ci.yml

[deps] Add Support for Django 5.x #155

---

django_loci/admin.py
django_loci/base/admin.py
django_loci/base/models.py
django_loci/static/django-loci/js/floorplan-inlines.js
django_loci/static/django-loci/js/loci.js
django_loci/tests/base/test_admin_inline.py
django_loci/tests/base/test_models.py

Closes #156 
Synchronize location type and clean 'indoor' value in clean function of 'AbstractObjectLocationForm'. 
Also added restriction to user from changing type from indoor to outdoor by adding 'floorplans' checks.

[admin] Fixed 'invalid value' error on location type change #156

---

django_loci/channels/base.py
django_loci/tests/base/test_channels.py
tests/openwisp2/settings.py

Related to #160
Improved test by utilizing async support from Django.
**Blockers**

[websocket] Improved connect/dissconnect methods of BaseLocationBroadcast #160

---

.github/workflows/ci.yml
README.rst
django_loci/static/django-loci/js/loci.js
django_loci/tests/__init__.py
django_loci/tests/base/test_admin_inline.py
django_loci/tests/base/test_selenium.py
django_loci/tests/test_selenium.py
django_loci/widgets.py

Closes #166.
Django release 5.1 has removed support for handling dimensions of geometry widget which led to geometry field not visible. Now we are using `LeafletAdminWidget` which provides css for dimensions of geometry widget.
Added selenium test cases for the above case to test visibility of map.

[fix] Fixed Geometry Map visibility django 5.2 #166

---

README.rst
conftest.py
django_loci/__init__.py
django_loci/apps.py
django_loci/base/admin.py
django_loci/base/geocoding_views.py
django_loci/base/models.py
django_loci/channels/asgi.py
django_loci/channels/base.py
django_loci/channels/receivers.py
django_loci/migrations/0001_initial.py
django_loci/settings.py
django_loci/tests/__init__.py
django_loci/tests/base/test_admin.py
django_loci/tests/base/test_admin_inline.py
django_loci/tests/base/test_apps.py
django_loci/tests/base/test_channels.py
django_loci/tests/base/test_models.py
django_loci/tests/base/test_selenium.py
django_loci/tests/testdeviceapp/migrations/0001_initial.py
django_loci/widgets.py
runtests.py
setup.py
tests/openwisp2/settings.py
tests/openwisp2/urls.py

Switched to double quotes (black formatter).

[qa] Switched to double quotes (black formatter)

---

CHANGES.rst
django_loci/__init__.py
django_loci/admin.py
django_loci/base/admin.py
django_loci/base/models.py
django_loci/channels/base.py
django_loci/static/django-loci/css/floorplan-widget.css
django_loci/static/django-loci/css/loci.css
django_loci/static/django-loci/js/floorplan-inlines.js
django_loci/static/django-loci/js/floorplan-widget.js
django_loci/static/django-loci/js/loci.js
django_loci/static/leaflet/draw/leaflet.draw.i18n.js
django_loci/tests/__init__.py
django_loci/tests/base/test_admin.py
django_loci/tests/base/test_admin_inline.py
django_loci/tests/base/test_models.py

Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>
---
All commits in the master branch since 1.1.2 tag: https://github.com/openwisp/django-loci/compare/1.1.2...master
Commits included for the 1.1.3 release: https://github.com/openwisp/django-loci/compare/1.1.2...release/1.1.3

1.1.3 release

---

CHANGES.rst
setup.py

GitHub release: https://github.com/openwisp/django-loci/releases/tag/1.1.3
PyPI release: https://pypi.org/project/django-loci/1.1.3/

[docs] Added changelog for 1.1.3 version

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/workflows/ci.yml
.github/workflows/pypi.yml
.prettierignore
django_loci/static/django-loci/js/floorplan-inlines.js
django_loci/static/django-loci/js/floorplan-widget.js
django_loci/static/django-loci/js/loci.js
django_loci/tests/base/static/test-geocode-invalid-address.json
django_loci/tests/base/static/test-geocode.json
django_loci/tests/base/static/test-reverse-geocode.json
django_loci/tests/base/static/test-reverse-location-with-no-address.json
run-qa-checks

Run prettier linting during qa-checks.

[qa] Updated formatting of js, json, yaml, md files
