runflake8, setup.cfg
Any `runflake8` or `runisort` script which
uses any command line options are moved
to the `setup.cfg` as it's done in [django-freeradius](https://github.com/openwisp/django-freeradius),
which is cleaner and easier to review.
Closes #16
=> [qa] Cleanup isort and flake8 settings

README.rst, requirements.txt
Closes #23 
I have updated pillow to be version 6 or higher and installed it successfully (might need to edit the docs about install gdal-bin via apt), and floor-plans and locations hopefully work as needed.
=> [dependencies] Updated Pillow

django_loci/static/django-loci/js/loci.js
`$geoRows.hide()` causing the loci coords fields to hidden by default, even if error occurs.
It's because *initially*, locationSelectionChange will **not** reset the form, so when user already set the `Location selection` and `Type` field then try to save it, if there's an error occurs, then `.loci.coords .form-row` fields will be hidden nevertheless because this `$geoRows.hide()` calls, even though the fields should not be hidden. This of course can confuse users because the UI inconsistency.
Closes #38
=> [ux] Fix loci fields hidden when error occurs

setup.py
It should be `Independent` and not `Indipendent`
:smile:
=> [typo] Correcting Independent spelling

django_loci/static/django-loci/css/loci.css
Sets the flex direction of the inner div wrapping the elements in the .form-row.field_geometry div to column when the screen size is less than 768px.
Fixes #43
=> [ux] When WebUI is too narrow geography map disappears

django_loci/base/admin.py, django_loci/base/models.py, django_loci/static/django-loci/js/loci.js, django_loci/tests/base/test_admin_inline.py, django_loci/tests/base/test_models.py
Fixed the issue by adding a confirmation script to the
loci.js which gives the opportunity to the admin to
confirm if he/she wish to save the indoor location
without indoor coords. Also modified the admin to make
sure this is saved without validation errors.
I also modified the model of object_location to allow
indoors to be None when type is indoor and no floorplan
is provided.
Fixes #54
=> [model] Allow indoor location without indoor coords #54

django_loci/static/django-loci/js/loci.js
- simplified: if no indoor coordinates and the object is new
simply ask if user wants to save without coords
- manage new case when the page first loads
- don't trigger the confirmation message on existing objects
=> [js] Improvements to indoor without coords

django_loci/static/django-loci/css/loci.css, django_loci/static/django-loci/js/loci.js
=> [bug] Websocket connect error #63

django_loci/settings.py
Setting name of `DJANGO_LOCI_GEOCODE_STRICT_TEST` should be the same as in settings, app_settings and docs.
=> [fix] Fix strict_test setting naming

django_loci/base/models.py, django_loci/storage.py, django_loci/tests/base/test_admin.py, django_loci/tests/base/test_models.py
The previous code used the "os" module for deleting resisdual
floorplan image files. This causes issues when the project uses
a file storage backend other than based on file system.
Added OverwriteMixin to extend storage classes to provide
overwrite functionality to the storage backend.
=> [fix] Use storage backend method for deleting FloorPlan.image

django_loci/storage.py
The DEFAULT_STORAGE_CLASS will be used for creating OverwriteStorage class.
Closes #107
=> [change] Use DEFAULT_STORAGE_CLASS as base for OverwriteStorage #107

django_loci/base/admin.py, django_loci/tests/base/test_admin.py
When selecting a location object via a popup window in the `floorplan` admin add view, display only **indoor locations**.
Fixes #93
=> [fix:ux] Fixed outdoor location selection in floorplans #93

django_loci/tests/base/test_admin.py
Fixed a failing indoor location test in the `'geo'` app of `openwisp-controller` by modifying the `filter_url` to consider the `app_label` during execution. Previously, the test `'test_floorplan_add_view_filters_indoor_location'` was failing due to a hardcoded `filter_url`.
=> [fix] Fixed failing of indoor location test in openwisp-controller

.coveragerc, .github/workflows/ci.yml, .gitignore, README.rst, django_loci/__init__.py, requirements-test.txt, requirements.txt, tests/openwisp2/settings.py
- Dropped support for Python 3.7
- Dropped support for Django 3.0 and 3.1
- Added support for Python 3.10
- Bumped django-leaflet~=0.28.0
- Bumped Pillow~=9.4.0
- Bumped geopy~=2.2.0
=> [deps] Added support for Django 4.1.0 and 4.2.0 

django_loci/static/django-loci/css/loci.css, django_loci/static/django-loci/js/loci.js
In Django 4.2, the window name scheme for related object lookup changed. This caused bug in triggering change event for the location field.
Related to #115
=> [fix] Fixed location inline form on Django 4.2 #115

CHANGES.rst, django_loci/__init__.py, requirements-test.txt, requirements.txt, setup.py
=> 1.1.0 release

django_loci/base/admin.py
=> [refactor] Added helper methods in AbstractObjectLocationForm

.github/workflows/ci.yml, django_loci/admin.py, django_loci/base/admin.py, django_loci/tests/base/test_admin_inline.py
Related to #157
Please [open a new issue](https://github.com/openwisp/django-loci/issues/new/choose) if there isn't an existing issue yet.
Moved logic for rejecting floorplan for outdoor location from django_loci.admin.LocationAdmin to django_loci.base.admin.AbstractLocationAdmin to ensure the extendability.
Removed code for Django 3.2
=> [refactor] Simplify formset handling for outdoor locations in admin $157

django_loci/admin.py, django_loci/base/admin.py, django_loci/channels/base.py, django_loci/static/django-loci/css/floorplan-widget.css, django_loci/static/django-loci/css/loci.css, django_loci/static/django-loci/js/floorplan-inlines.js, django_loci/static/django-loci/js/floorplan-widget.js, django_loci/static/django-loci/js/loci.js, django_loci/tests/base/test_admin.py, django_loci/tests/base/test_admin_inline.py
Closes #95.
For view only permission, django admin uses 'AdminReadonlyField' for rendering data which looks for form fields in the model instance. And for widget to render 'read_only' must be set True. Setting the attributes to instance and 'read_only' geometry widget allowed the data to be viewed and map to render.
=> [fix] Fixed ObjectLocation admin read-only mode #95

django_loci/base/admin.py, django_loci/tests/__init__.py, django_loci/tests/base/test_admin.py, django_loci/tests/base/test_admin_inline.py, django_loci/tests/base/test_selenium.py
The get_formset_kwargs method was previously part of AbstractObjectLocationInline, which is specific to models using generic foreign keys.
Moving it to ObjectLocationMixin ensures the method is available to all models, improving reusability and consistency.
=> [chores] Migrate formset function to base objectlocation mixin

django_loci/static/django-loci/css/loci.css
=> [css:django 5] Hide redundant heading in ObjectLocationInline

.github/workflows/ci.yml, README.rst, django_loci/channels/receivers.py, django_loci/static/django-loci/js/loci.js, django_loci/tests/base/test_channels.py, django_loci/tests/base/test_selenium.py, django_loci/tests/test_selenium.py, runtests, runtests.py, tests/openwisp2/settings.py
Added address update handling in the websocket message and updated listenForLocationUpdates logic accordingly.
Fixes #169
Closes #169.
- Updated the real-time update logic to include address field updates via WebSocket.
- Modified the `listenForLocationUpdates` function to handle and broadcast address changes.
- Inheriting from `ChannelLiveServerTestCase` is causing test failures in Django 5.2, which is a new release, and a fix has yet to be released for it.
- Adding `ChannelLiveServerTestCase` prevents running tests in parallel with the --parallel flag, as it relies on live WebSocket connections that cannot run concurrently.
[real-time-address.webm](https://github.com/user-attachments/assets/9cec1fda-b51e-4db9-8e32-cc02050fee20)
=> [fix] Added address field to real-time location updates #169
